title: Envault Documentation
description: Your data, your way
logo: "/assets/images/envault.png"
favicon_ico: "/assets/images/favicon.ico"
theme: just-the-docs
url: https://docs.envault.io
aux_links:
  envault.io: https://envault.io
  Envault Docs on GitHub: https://github.com/envault-io/envault
aux_links_new_tab: true
